python train_RF_model.py -f ap
python train_RF_model.py -f ap-4096
python train_RF_model.py -f morgan2
python train_RF_model.py -f morgan2-4096
python train_RF_model.py -f rdk5
python train_RF_model.py -f rdk5-4096
python train_LR_model.py -f ap
python train_LR_model.py -f ap-4096
python train_LR_model.py -f morgan2
python train_LR_model.py -f morgan2-4096
python train_LR_model.py -f rdk5
python train_LR_model.py -f rdk5-4096
